name: 'Build'

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  ci-checks:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js from .tool-versions
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run this action (test)
        id: mvnd
        uses: ./
        with:
          version: '1.0.2'
      - name: Echo mvnd binary path
        run: echo "The mvnd binary was saved to ${{ steps.mvnd.outputs.cached-binary-path }}"